### ISSUE TITLE
Reference to the Intersection Observer is missing in the plugin path.

### ISSUE THREAD

**Issue by jeffreynolte** [MarcinKilarski/lozad-observer-lazy-load#1]
Seems like simply linking the library in a similar fashion to yall would do the trick.
https://www.npmjs.com/package/intersection-observer

This occurence is present on line 10:
https://github.com/MarcinKilarski/lozad-observer-lazy-load/blob/master/lozad-observer-lazy-load/lozad-observer-lazy-load.php#L10

**Comment by MarcinKilarski** [comment]
Thanks for drawing my attention to this. You are awesome!

I have added a link to the polyfill via polyfill.io.
